# Module: Monedas
# Document : modules/Monedas/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 02.02.2014 01:15:20
#
---
Monedas:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  modulosRelacionables: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withMetadata: '0'
  addMetadata: '0'
  deleteMetadata: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: Codigo
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: Codigo
  fieldGeneratorMetatagDescription: Codigo
  fieldGeneratorMetatagKeywords: Codigo
  controller: Monedas
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Monedas
  id_video: monedas
  url_video: null
  feature_list: YES
  conection: ''
  entity: Monedas
  table: ErpMonedas
  primarykey: IDMoneda
  linkBy: ''
  records_per_page: 15
  order_by:
    -
      title: 'Moneda a-z'
      criteria: 'Moneda ASC'
    -
      title: 'Moneda z-a'
      criteria: 'Moneda DESC'
  search_default: Moneda
  referenced_entities:
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDMoneda:
      title: IDMoneda
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    Codigo:
      title: Codigo
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '3', min: null, max: null, message: 'Valor Requerido' }
    Moneda:
      title: Moneda
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
    Simbolo:
      title: Simbolo
      filter: YES
      list: YES
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: YES, type: string, length: '255', min: null, max: null, message: 'Valor Requerido' }
