# Module: RutasRepartoDetalle
# Document : modules\RutasRepartoDetalle\config.yml
#
# @author Sergio PÃ©rez <sergio.perez@albatronic.com>
# @copyright INFORMATICA ALBATRONIC SL
# @since 14.05.2012 18:12:47
#
---
RutasRepartoDetalle:
  login_required: true
  permission_control: true
  favourite_control: NO
  help_file: help.html.twig
  title: RutasRepartoDetalle
  id_video: rutasrepartodetalle
  url_video: null
  conection: 'datos<?php echo $_SESSION['emp'];?>'
  entity: RutasRepartoDetalle
  table: rutas_reparto_detalle
  primarykey: Id
  linkBy: IDRuta
  records_per_page: 10
  order_by: Id
  search_default: Id
  referenced_entities:
    -
      entity: RutasReparto
    -
      entity: Agentes
    -
      entity: Zonas
    -
      entity: ClientesDentrega
  columns:
    -
      title: Id
      field: Id
      filter: false
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
    -
      title: Ruta
      field: IDRuta
      filter: false
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      aditional_filter:
        order: 1
        caption: IDRuta
        entity: RutasReparto
        method: fetchAll
        params: null
        type: input
        operator: =
        event: null
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    -
      title: Repartidor
      field: IDRepartidor
      filter: false
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      aditional_filter:
        order: 2
        caption: IDRepartidor
        entity: Agentes
        method: fetchAll
        params: null
        type: input
        operator: =
        event: null
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    -
      title: Dia
      field: Dia
      filter: false
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      aditional_filter:
        order: 3
        caption: Dia
        entity: ValoresSN
        method: fetchAll
        params: null
        type: select
        operator: =
        event: null
      validator:
        nullable: NO
        type: tinyint
        length: 1
        min: null
        max: null
        message: Valor Requerido
    -
      title: OrdenZona
      field: OrdenZona
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDZona
      field: IDZona
      filter: false
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      aditional_filter:
        order: 4
        caption: IDZona
        entity: Zonas
        method: fetchAll
        params: null
        type: input
        operator: =
        event: null
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    -
      title: OrdenDirec
      field: OrdenDirec
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    -
      title: IDDirec
      field: IDDirec
      filter: false
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
        link: null
      default: 
      aditional_filter:
        order: 5
        caption: IDDirec
        entity: ClientesDentrega
        method: fetchAll
        params: null
        type: input
        operator: =
        event: null
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
