# Module: ErpAlmacenesMapas
# Document : modules/ErpAlmacenesMapas/config.yml
#
# @author: Sergio Pérez <sergio.perez@albatronic.com>
# @copyright: Informática ALBATRONIC SL
# @date 25.03.2013 20:02:24
#
---
AlmacenesMapas:
  app: ''
  isModuleRoot: 0
  linkModule:
    fromColumn: ''
    toEntity: ''
    toColumn: ''
  translatable: false
  searchable: false
  showCommonFields: false
  numMaxRecords: ''
  numberOfImages: '0'
  withGalery: '0'
  withDocuments: '0'
  withVideos: 0
  withAudios: '0'
  maxSizes:
    image: '400000'
    document: ''
    video: ''
    audio: ''
  galery:
    maxWidthImage: '500'
    maxHeightImage: '400'
    generateThumbnail: '0'
    widthThumbnail: '50'
    heightThumbnail: '50'
  urlFriendlyManagement: false
  fieldGeneratorUrlFriendly: IDAlmacen
  metatagTitleManagement: false
  fieldGeneratorMetatagTitle: IDAlmacen
  controller: AlmacenesMapas
  action: Index
  template: index.html.twig
  parametros: ''
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
  favourite_control: NO
  help_file: help.html.twig
  title: Mapa de almacén
  id_video: almacenesmapas
  url_video: null
  feature_list: YES
  conection: ''
  entity: AlmacenesMapas
  table: ErpAlmacenesMapas
  primarykey: IDUbicacion
  linkBy: IDAlmacen
  records_per_page: 15
  order_by:
    -
      title: 'IDUbicacion a-z'
      criteria: 'IDUbicacion ASC'
    -
      title: 'IDUbicacion z-a'
      criteria: 'IDUbicacion DESC'
  search_default: IDUbicacion
  referenced_entities:
    - ErpAlmacenes
    - ValoresSN
    - ValoresPrivacy
    - ValoresDchaIzq
    - ValoresChangeFreq
    - RequestMethods
    - RequestOrigins
    - CpanAplicaciones
  columns:
    IDUbicacion:
      title: IDUbicacion
      visible: false
      updatable: false
      filter: NO
      list: NO
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
    IDAlmacen:
      title: IDAlmacen
      filter: NO
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      #aditional_filter: { order: 1, caption: IDAlmacen, entity: ErpAlmacenes, method: fetchAll, params: Descripcion, type: select, operator: '=', event: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Ubicacion:
      title: Ubicación
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: null
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: string, length: '15', min: null, max: null, message: 'Valor Requerido' }
    X:
      title: X
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Y:
      title: Y
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Z:
      title: Z
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '11', min: null, max: null, message: 'Valor Requerido' }
    Alto:
      title: Alto
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Ancho:
      title: Ancho
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
    Fondo:
      title: Fondo
      filter: YES
      list: NO
      visible: true
      updatable: true
      default: '0.00'
      help: null
      permission: null
      translatable: false
      searchable: false
      link: { route: null, param: null, title: null, target: null, link: null }
      validator: { nullable: NO, type: integer, length: '10', min: null, max: null, message: 'Valor Requerido' }
