# Module: RecepcionarCab
#
# @author Sergio Perez <sergio.perez@albatronic.com>
# @copyright Informatica ALBATRONIC
# @since: 27-11-2011
#
---
RecepcionarCab:
  login_required: true
  permission_control: true
  help_file: help.html.twig
  title: Recepcionar Mercanc√≠a
  conection: ''
  entity: RecepcionarCab
  table: pedidos_cab
  primarykey: IDPedido
  records_per_page: 10
  order_by: Fecha
  search_default: IDPedido
  columns:
    - 
      title: Pedido
      field: IDPedido
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator: null
    - 
      title: Sucursal
      field: IDSucursal
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 000
      validator:
        nullable: NO
        type: integer
        length: 3
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Almacen
      field: IDAlmacen
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 000
      validator:
        nullable: NO
        type: integer
        length: 3
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Agente
      field: IDAgente
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Su Pedido
      field: SuPedido
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: true
        type: string
        length: 15
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Referencia
      field: Referencia
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: true
        type: string
        length: 15
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Fecha Pedido
      field: Fecha
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0000-00-00
      validator:
        nullable: NO
        type: date
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Fecha Prev. Entrega
      field: FechaEntrega
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0000-00-00
      validator:
        nullable: NO
        type: date
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Fecha Recepcion
      field: FechaEntrada
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0000-00-00
      validator:
        nullable: NO
        type: date
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Proveedor
      field: IDProveedor
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: integer
        length: 11
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Importe
      field: Importe
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Descuento
      field: Descuento
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: BaseImponible1
      field: BaseImponible1
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: true
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Iva1
      field: Iva1
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: CuotaIva1
      field: CuotaIva1
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: true
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Recargo1
      field: Recargo1
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: true
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: CuotaRecargo1
      field: CuotaRecargo1
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: true
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: BaseImponible2
      field: BaseImponible2
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Iva2
      field: Iva2
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: CuotaIva2
      field: CuotaIva2
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Recargo2
      field: Recargo2
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: CuotaRecargo2
      field: CuotaRecargo2
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: BaseImponible3
      field: BaseImponible3
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Iva3
      field: Iva3
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: CuotaIva3
      field: CuotaIva3
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Recargo3
      field: Recargo3
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: CuotaRecargo3
      field: CuotaRecargo3
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: TotalBases
      field: TotalBases
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: TotalIva
      field: TotalIva
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: TotalRecargo
      field: TotalRecargo
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Total
      field: Total
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0.00
      validator:
        nullable: NO
        type: decimal
        length: 10
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Observaciones
      field: Observaciones
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: true
        type: string
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Clave
      field: Clave
      filter: true
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: true
        type: string
        length: 50
        min: null
        max: null
        message: Valor Requerido
    - 
      title: FActualizacion
      field: FActualizacion
      filter: true
      list: false
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0000-00-00 00:00:00
      validator:
        nullable: true
        type: datetime
        length: null
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Estado
      field: IDEstado
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 1
        min: null
        max: null
        message: Valor Requerido
    - 
      title: IDFP
      field: IDFP
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: 0
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
    - 
      title: Agencia de Tpte.
      field: IDAgencia
      filter: true
      list: true
      form: true
      link:
        route: null
        param: null
        title: null
        target: null
      default: null
      validator:
        nullable: NO
        type: integer
        length: 4
        min: null
        max: null
        message: Valor Requerido
